"""
Phase 4: Build and Train the Hierarchical Fusion Model (Main Contribution)
==========================================================================
Description:
    Implements the proposed HierarchicalMuRIL model combining sentence-level [CLS] representations
    with a learned token-level word attention mechanism. Also implements the WordOnlyMuRIL
    ablation model. Trains both models, evaluates on the test set, saves PyTorch weights,
    and prints a 4-model performance comparison.

Dependencies:
    - phase2_data.joblib (Generated by phase2_preprocessing.py)
    - phase3_results.joblib (Generated by phase3_baselines.py)
    - phase2_preprocessing.py (Imports TanglishDataset)

Outputs:
    - hier_model.pt: PyTorch saved weights for proposed HierarchicalMuRIL model.
    - word_model.pt: PyTorch saved weights for WordOnlyMuRIL ablation model.
    - phase4_results.joblib: Contains all 4 model F1 scores for Phase 5 evaluation.
"""

import os
import copy
import joblib
import torch
import torch.nn as nn
import pandas as pd
from torch.optim import AdamW
from torch.utils.data import DataLoader
from transformers import AutoModel, AutoTokenizer, get_linear_schedule_with_warmup
from sklearn.metrics import f1_score, classification_report
from tqdm.auto import tqdm

# Import TanglishDataset from phase2_preprocessing
from phase2_preprocessing import TanglishDataset

# Setup Device and Constants
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
N_EPOCHS = 5
LR = 2e-5
BATCH_SIZE = 16
MAX_LEN = 128

# ==============================================================================
# Model Architecture 1: Proposed Hierarchical Fusion Model
# ==============================================================================
class HierarchicalMuRIL(nn.Module):
    """
    Hierarchical Hate Speech Detection Model for Code-Mixed Tanglish.
    Fuses sentence-level [CLS] vector (768) + learned word-attention vector (768).
    """
    def __init__(self, model_name: str = "google/muril-base-cased", num_classes: int = 5, dropout_rate: float = 0.3):
        super(HierarchicalMuRIL, self).__init__()

        self.encoder = AutoModel.from_pretrained(model_name)
        self.word_attn = nn.Linear(768, 1)

        self.fusion = nn.Sequential(
            nn.Linear(768 * 2, 768),
            nn.ReLU(),
            nn.Dropout(dropout_rate)
        )

        self.classifier = nn.Linear(768, num_classes)
        self.dropout = nn.Dropout(dropout_rate)

    def forward(self, input_ids, attention_mask):
        encoder_outputs = self.encoder(input_ids=input_ids, attention_mask=attention_mask)
        last_hidden_state = encoder_outputs.last_hidden_state

        # 1. Sentence Signal ([CLS] token)
        cls_vec = last_hidden_state[:, 0, :]

        # 2. Word Signals (all tokens except [CLS])
        token_vecs = last_hidden_state[:, 1:, :]
        token_mask = attention_mask[:, 1:]

        # 3. Masked Softmax Word Attention
        attn_scores = self.word_attn(token_vecs).squeeze(-1)
        attn_scores = attn_scores.masked_fill(token_mask == 0, -1e9)
        attn_weights = torch.softmax(attn_scores, dim=-1).unsqueeze(-1)

        # 4. Weighted Word Signal
        word_vec = torch.sum(token_vecs * attn_weights, dim=1)

        # 5. Concatenation & Fusion
        fused_vec = torch.cat([cls_vec, word_vec], dim=-1)
        fused_vec = self.dropout(fused_vec)

        fusion_out = self.fusion(fused_vec)
        logits = self.classifier(fusion_out)

        return logits


# ==============================================================================
# Model Architecture 2: Word-Only Ablation Model
# ==============================================================================
class WordOnlyMuRIL(nn.Module):
    """
    Ablation model using ONLY word-level attention mechanism (No [CLS] token vector).
    """
    def __init__(self, model_name: str = "google/muril-base-cased", num_classes: int = 5, dropout_rate: float = 0.3):
        super(WordOnlyMuRIL, self).__init__()

        self.encoder = AutoModel.from_pretrained(model_name)
        self.word_attn = nn.Linear(768, 1)

        self.classifier = nn.Sequential(
            nn.Dropout(dropout_rate),
            nn.Linear(768, 768),
            nn.ReLU(),
            nn.Dropout(dropout_rate),
            nn.Linear(768, num_classes)
        )

    def forward(self, input_ids, attention_mask):
        encoder_outputs = self.encoder(input_ids=input_ids, attention_mask=attention_mask)
        last_hidden_state = encoder_outputs.last_hidden_state

        token_vecs = last_hidden_state[:, 1:, :]
        token_mask = attention_mask[:, 1:]

        attn_scores = self.word_attn(token_vecs).squeeze(-1)
        attn_scores = attn_scores.masked_fill(token_mask == 0, -1e9)
        attn_weights = torch.softmax(attn_scores, dim=-1).unsqueeze(-1)

        word_vec = torch.sum(token_vecs * attn_weights, dim=1)
        logits = self.classifier(word_vec)
        return logits


# ==============================================================================
# Training & Evaluation Orchestrator
# ==============================================================================
def train_hierarchical(model, train_loader, dev_loader, class_weights, n_epochs=5, lr=2e-5):
    """Trains custom PyTorch models returning raw logits."""
    criterion = nn.CrossEntropyLoss(weight=class_weights.to(DEVICE))
    optimizer = AdamW(model.parameters(), lr=lr, weight_decay=0.01)

    num_training_steps = len(train_loader) * n_epochs
    num_warmup_steps = int(0.10 * num_training_steps)
    scheduler = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps=num_warmup_steps,
        num_training_steps=num_training_steps
    )

    best_dev_f1 = 0.0
    best_weights = None

    for epoch in range(1, n_epochs + 1):
        model.train()
        train_loss = 0.0

        for batch in tqdm(train_loader, desc=f"Epoch {epoch} Training", leave=False):
            input_ids = batch['input_ids'].to(DEVICE)
            attention_mask = batch['attention_mask'].to(DEVICE)
            labels = batch['label'].to(DEVICE)

            optimizer.zero_grad()
            logits = model(input_ids=input_ids, attention_mask=attention_mask)
            loss = criterion(logits, labels)

            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

            optimizer.step()
            scheduler.step()

            train_loss += loss.item()

        avg_train_loss = train_loss / len(train_loader)
        dev_f1, _, _, avg_dev_loss = test_hierarchical(model, dev_loader, criterion)

        print(f"Epoch {epoch}/{n_epochs} | Train Loss: {avg_train_loss:.4f} | Dev Loss: {avg_dev_loss:.4f} | Dev Macro F1: {dev_f1:.4f}")

        if dev_f1 > best_dev_f1:
            best_dev_f1 = dev_f1
            best_weights = copy.deepcopy(model.state_dict())
            print(f"  🏆 New Best Dev Macro F1: {best_dev_f1:.4f}")

    if best_weights is not None:
        model.load_state_dict(best_weights)

    return model, best_dev_f1


def test_hierarchical(model, loader, criterion=None):
    """Evaluates custom PyTorch model on a loader."""
    model.eval()
    all_preds = []
    all_labels = []
    total_loss = 0.0

    if criterion is None:
        criterion = nn.CrossEntropyLoss()

    with torch.no_grad():
        for batch in tqdm(loader, desc="Evaluating", leave=False):
            input_ids = batch['input_ids'].to(DEVICE)
            attention_mask = batch['attention_mask'].to(DEVICE)
            labels = batch['label'].to(DEVICE)

            logits = model(input_ids=input_ids, attention_mask=attention_mask)
            loss = criterion(logits, labels)
            total_loss += loss.item()

            preds = torch.argmax(logits, dim=1).cpu().numpy()
            all_preds.extend(preds)
            all_labels.extend(labels.cpu().numpy())

    macro_f1 = f1_score(all_labels, all_preds, average="macro", zero_division=0)
    avg_loss = total_loss / len(loader)
    return macro_f1, all_preds, all_labels, avg_loss


# ==============================================================================
# Main Execution Pipeline
# ==============================================================================
def main():
    p2_file = "phase2_data.joblib"
    p3_file = "phase3_results.joblib"

    if not os.path.exists(p2_file) or not os.path.exists(p3_file):
        raise FileNotFoundError(f"Missing prerequisites. Please run phase2_preprocessing.py and phase3_baselines.py first!")

    print("Loading preprocessed data and baseline results...")
    data_p2 = joblib.load(p2_file)
    data_p3 = joblib.load(p3_file)

    train_df      = data_p2['train_df']
    dev_df        = data_p2['dev_df']
    test_df       = data_p2['test_df']
    class_weights = data_p2['class_weights']
    label2id      = data_p2['label2id']

    test_f1_xlmr      = data_p3['test_f1_xlmr']
    test_f1_muril     = data_p3['test_f1_muril']
    best_dev_f1_xlmr  = data_p3['best_dev_f1_xlmr']
    best_dev_f1_muril = data_p3['best_dev_f1_muril']

    # Tokenizer & DataLoaders
    tokenizer = AutoTokenizer.from_pretrained("google/muril-base-cased")
    train_dataset = TanglishDataset(train_df, tokenizer, max_len=MAX_LEN)
    dev_dataset   = TanglishDataset(dev_df, tokenizer, max_len=MAX_LEN)
    test_dataset  = TanglishDataset(test_df, tokenizer, max_len=MAX_LEN)

    train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
    dev_loader   = DataLoader(dev_dataset, batch_size=BATCH_SIZE, shuffle=False)
    test_loader  = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

    target_names = list(label2id.keys())
    criterion = nn.CrossEntropyLoss(weight=class_weights.to(DEVICE))

    # --------------------------------------------------------------------------
    # 1. Train Proposed Hierarchical Model
    # --------------------------------------------------------------------------
    print("\n🚀 Training Full Hierarchical Fusion Model (Sentence + Word Attention)...")
    hier_model = HierarchicalMuRIL().to(DEVICE)
    hier_model, best_dev_f1_hier = train_hierarchical(hier_model, train_loader, dev_loader, class_weights, n_epochs=N_EPOCHS, lr=LR)
    test_f1_hier, hier_preds, hier_labels, _ = test_hierarchical(hier_model, test_loader, criterion)

    print(f"\n📊 --- Proposed Hierarchical Model Test Results ---")
    print(f"Test Macro F1: {test_f1_hier:.4f}\n")
    print(classification_report(hier_labels, hier_preds, target_names=target_names, digits=4, zero_division=0))
    torch.save(hier_model.state_dict(), "hier_model.pt")

    # --------------------------------------------------------------------------
    # 2. Train Word-Only Ablation Model
    # --------------------------------------------------------------------------
    print("\n🔬 Training Ablation Model (Word Attention Only)...")
    word_model = WordOnlyMuRIL().to(DEVICE)
    word_model, best_dev_f1_word = train_hierarchical(word_model, train_loader, dev_loader, class_weights, n_epochs=N_EPOCHS, lr=LR)
    test_f1_word, word_preds, word_labels, _ = test_hierarchical(word_model, test_loader, criterion)

    print(f"\n📊 --- Word-Only Ablation Model Test Results ---")
    print(f"Test Macro F1: {test_f1_word:.4f}\n")
    print(classification_report(word_labels, word_preds, target_names=target_names, digits=4, zero_division=0))
    torch.save(word_model.state_dict(), "word_model.pt")

    # --------------------------------------------------------------------------
    # 3. Final 4-Model Results Comparison Table
    # --------------------------------------------------------------------------
    final_comparison_df = pd.DataFrame({
        "Model Architecture": [
            "Baseline A: XLM-RoBERTa (Sentence-Only)",
            "Baseline B: MuRIL (Sentence-Only)",
            "Ablation Model: MuRIL (Word-Attention Only)",
            "Proposed Model: Hierarchical MuRIL (Sentence + Word Fusion)"
        ],
        "Dev Macro F1": [
            f"{best_dev_f1_xlmr:.4f}",
            f"{best_dev_f1_muril:.4f}",
            f"{best_dev_f1_word:.4f}",
            f"{best_dev_f1_hier:.4f}"
        ],
        "Test Macro F1": [
            f"{test_f1_xlmr:.4f}",
            f"{test_f1_muril:.4f}",
            f"{test_f1_word:.4f}",
            f"{test_f1_hier:.4f}"
        ]
    })

    print("=" * 75)
    print("     HIERARCHICAL HATE SPEECH DETECTION FOR TANGLISH - FINAL RESULTS      ")
    print("=" * 75)
    print(final_comparison_df.to_string(index=False))
    print("=" * 75)

    output_file = "phase4_results.joblib"
    joblib.dump({
        "test_f1_xlmr": test_f1_xlmr,
        "test_f1_muril": test_f1_muril,
        "test_f1_word": test_f1_word,
        "test_f1_hier": test_f1_hier,
        "best_dev_f1_xlmr": best_dev_f1_xlmr,
        "best_dev_f1_muril": best_dev_f1_muril,
        "best_dev_f1_word": best_dev_f1_word,
        "best_dev_f1_hier": best_dev_f1_hier
    }, output_file)
    print(f"\n✅ Phase 4 completed successfully! Saved all model results to '{output_file}'.")

if __name__ == "__main__":
    main()
