"""
Phase 2: Preprocessing Pipeline and Tanglish Slang Normalization
================================================================
Description:
    Defines the TANGLISH_SLANG semantic tagging dictionary and text normalization function.
    Applies normalization across train/dev/test sets, computes balanced class weights,
    defines the PyTorch TanglishDataset class, and creates MuRIL DataLoaders.

Dependencies:
    - phase1_data.joblib (Generated by phase1_setup.py)

Outputs:
    - phase2_data.joblib: Contains preprocessed DataFrames, class_weights, and label2id.
"""

import os
import re
import joblib
import numpy as np
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
from sklearn.utils.class_weight import compute_class_weight
from transformers import AutoTokenizer

# ==============================================================================
# Step 1: Slang Dictionary & Normalization Function
# ==============================================================================
TANGLISH_SLANG = {
    # Dismissal terms
    "poda": "[DISMISSAL]",
    "podi": "[DISMISSAL]",
    "ponga": "[DISMISSAL]",

    # Stupid / Fool slurs
    "loosu": "[SLUR_STUPID]",
    "losu": "[SLUR_STUPID]",
    "kena": "[SLUR_STUPID]",
    "mutti": "[SLUR_STUPID]",

    # Animal slurs
    "naaye": "[SLUR_ANIMAL]",
    "naye": "[SLUR_ANIMAL]",
    "kazhudhai": "[SLUR_ANIMAL]",
    "panni": "[SLUR_ANIMAL]",

    # Profanity
    "thevdiya": "[PROFANITY]",
    "thevidiya": "[PROFANITY]",
    "otha": "[PROFANITY]",

    # Caste / Group slurs
    "paarpan": "[GROUP_SLUR]",
    "parpan": "[GROUP_SLUR]",

    # Derogatory address terms
    "dei": "[ADDRESS_DEROG]",
    "daa": "[ADDRESS_DEROG]",
}

def normalize_tanglish(text: str) -> str:
    """
    Cleans and normalizes Tanglish text: lowercasing, URL/hashtag/mention removal,
    repeated character reduction, and word-boundary slang semantic tagging.
    """
    if not isinstance(text, str):
        return ""

    text = text.lower()
    text = re.sub(r'https?://\S+|www\.\S+', '', text)
    text = re.sub(r'[@#]\S+', '', text)
    text = re.sub(r'(.)\1{2,}', r'\1\1', text)

    for word, tag in TANGLISH_SLANG.items():
        pattern = r'\b' + re.escape(word) + r'\b'
        text = re.sub(pattern, f"{word} {tag}", text)

    text = re.sub(r'\s+', ' ', text).strip()
    return text

# ==============================================================================
# Step 2: Custom PyTorch Dataset Class
# ==============================================================================
class TanglishDataset(Dataset):
    def __init__(self, df: pd.DataFrame, tokenizer, max_len: int = 128):
        self.texts = df['processed'].tolist()
        self.labels = df['label'].tolist()
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = str(self.texts[idx])
        label = self.labels[idx]

        encoding = self.tokenizer(
            text,
            truncation=True,
            padding='max_length',
            max_length=self.max_len,
            return_tensors='pt'
        )

        return {
            'input_ids': encoding['input_ids'].squeeze(0),
            'attention_mask': encoding['attention_mask'].squeeze(0),
            'label': torch.tensor(label, dtype=torch.long)
        }

# ==============================================================================
# Main Execution Pipeline
# ==============================================================================
def main():
    input_file = "phase1_data.joblib"
    if not os.path.exists(input_file):
        raise FileNotFoundError(f"Missing '{input_file}'. Please run phase1_setup.py first!")

    print(f"Loading raw data from '{input_file}'...")
    data = joblib.load(input_file)
    train_df = data['train_df']
    dev_df   = data['dev_df']
    test_df  = data['test_df']
    label2id = data['label2id']

    # 1. Apply Normalization
    print("Applying Tanglish slang normalization...")
    train_df['processed'] = train_df['text'].apply(normalize_tanglish)
    dev_df['processed']   = dev_df['text'].apply(normalize_tanglish)
    test_df['processed']  = test_df['text'].apply(normalize_tanglish)
    print("✅ Normalization completed.")

    # Print sample tagged rows
    tagged_samples = train_df[train_df['processed'].str.contains(r'\[', na=False)].head(5)
    print("\n--- 5 Sample Tagged Rows ---")
    for _, row in tagged_samples.iterrows():
        print(f"Original : {row['text']}")
        print(f"Processed: {row['processed']}")
        print(f"Category : {row['category']}")
        print("-" * 60)

    # 2. Compute Class Weights
    print("\nComputing balanced class weights...")
    unique_classes = np.unique(train_df['label'])
    weights = compute_class_weight(
        class_weight='balanced',
        classes=unique_classes,
        y=train_df['label'].values
    )
    class_weights = torch.tensor(weights, dtype=torch.float32)
    print("✅ Class weights tensor:", class_weights)

    # 3. Setup Tokenizer & DataLoaders
    MODEL_NAME = "google/muril-base-cased"
    print(f"\nLoading MuRIL tokenizer '{MODEL_NAME}'...")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

    BATCH_SIZE = 16
    MAX_LEN = 128

    train_dataset = TanglishDataset(train_df, tokenizer, max_len=MAX_LEN)
    dev_dataset   = TanglishDataset(dev_df, tokenizer, max_len=MAX_LEN)
    test_dataset  = TanglishDataset(test_df, tokenizer, max_len=MAX_LEN)

    train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
    dev_loader   = DataLoader(dev_dataset, batch_size=BATCH_SIZE, shuffle=False)
    test_loader  = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

    print(f"✅ DataLoaders created successfully (batch_size={BATCH_SIZE}):")
    print(f"  - Train Batches: {len(train_loader)}")
    print(f"  - Dev Batches:   {len(dev_loader)}")
    print(f"  - Test Batches:  {len(test_loader)}")

    # 4. Save processed data for Phase 3 & Phase 4
    output_file = "phase2_data.joblib"
    joblib.dump({
        "train_df": train_df,
        "dev_df": dev_df,
        "test_df": test_df,
        "class_weights": class_weights,
        "label2id": label2id
    }, output_file)
    print(f"\n✅ Phase 2 completed successfully! Saved preprocessed data to '{output_file}'.")

if __name__ == "__main__":
    main()
