"""
Phase 3: Train Baseline Models for Comparison (XLM-R & MuRIL Sentence-Only)
==========================================================================
Description:
    Trains and evaluates two sentence-level baseline models:
      1. Baseline A: XLM-RoBERTa (xlm-roberta-base)
      2. Baseline B: Google MuRIL Sentence-Only (google/muril-base-cased)
    Uses class-weighted CrossEntropyLoss, AdamW optimizer with linear warmup,
    and tracks Dev Macro F1 for best checkpoint selection.

Dependencies:
    - phase2_data.joblib (Generated by phase2_preprocessing.py)
    - phase2_preprocessing.py (Imports TanglishDataset)

Outputs:
    - xlmr_baseline.pt: PyTorch saved weights for XLM-R baseline.
    - muril_baseline.pt: PyTorch saved weights for MuRIL sentence-only baseline.
    - phase3_results.joblib: Contains baseline F1 scores for Phase 4 & 5 comparison.
"""

import os
import copy
import joblib
import torch
import torch.nn as nn
import pandas as pd
from torch.optim import AdamW
from torch.utils.data import DataLoader
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    get_linear_schedule_with_warmup
)
from sklearn.metrics import f1_score, classification_report
from tqdm.auto import tqdm

# Import TanglishDataset from phase2_preprocessing
from phase2_preprocessing import TanglishDataset

# Setup Device and Constants
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
N_EPOCHS = 5
LR = 2e-5
BATCH_SIZE = 16
MAX_LEN = 128

# ==============================================================================
# Helper Training & Evaluation Functions
# ==============================================================================
def train_epoch(model, loader, optimizer, scheduler, criterion, device):
    """Runs one training epoch with gradient clipping at 1.0."""
    model.train()
    total_loss = 0.0

    for batch in tqdm(loader, desc="Training", leave=False):
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['label'].to(device)

        optimizer.zero_grad()
        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        loss = criterion(outputs.logits, labels)

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

        optimizer.step()
        scheduler.step()

        total_loss += loss.item()

    return total_loss / len(loader)


def evaluate(model, loader, criterion, device):
    """Evaluates model performance on dev or test set loader."""
    model.eval()
    total_loss = 0.0
    all_preds = []
    all_labels = []

    with torch.no_grad():
        for batch in tqdm(loader, desc="Evaluating", leave=False):
            input_ids = batch['input_ids'].to(device)
            attention_mask = batch['attention_mask'].to(device)
            labels = batch['label'].to(device)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            loss = criterion(outputs.logits, labels)

            total_loss += loss.item()
            preds = torch.argmax(outputs.logits, dim=1).cpu().numpy()
            all_preds.extend(preds)
            all_labels.extend(labels.cpu().numpy())

    avg_loss = total_loss / len(loader)
    macro_f1 = f1_score(all_labels, all_preds, average="macro", zero_division=0)
    return avg_loss, macro_f1, all_preds, all_labels


def run_training(model_name, train_loader, dev_loader, class_weights, label2id):
    """Orchestrates baseline training and returns (best_model, best_dev_f1)."""
    print(f"\n==================================================")
    print(f"🚀 Initializing Baseline Model: '{model_name}'")
    print(f"==================================================")

    model = AutoModelForSequenceClassification.from_pretrained(
        model_name,
        num_labels=len(label2id)
    ).to(DEVICE)

    criterion = nn.CrossEntropyLoss(weight=class_weights.to(DEVICE))
    optimizer = AdamW(model.parameters(), lr=LR, weight_decay=0.01)

    num_training_steps = len(train_loader) * N_EPOCHS
    num_warmup_steps = int(0.10 * num_training_steps)
    scheduler = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps=num_warmup_steps,
        num_training_steps=num_training_steps
    )

    best_dev_f1 = 0.0
    best_model_weights = None

    for epoch in range(1, N_EPOCHS + 1):
        train_loss = train_epoch(model, train_loader, optimizer, scheduler, criterion, DEVICE)
        dev_loss, dev_f1, _, _ = evaluate(model, dev_loader, criterion, DEVICE)

        print(f"Epoch {epoch}/{N_EPOCHS} | Train Loss: {train_loss:.4f} | Dev Loss: {dev_loss:.4f} | Dev Macro F1: {dev_f1:.4f}")

        if dev_f1 > best_dev_f1:
            best_dev_f1 = dev_f1
            best_model_weights = copy.deepcopy(model.state_dict())
            print(f"  🏆 New best Dev Macro F1: {best_dev_f1:.4f}")

    if best_model_weights is not None:
        model.load_state_dict(best_model_weights)

    return model, best_dev_f1


# ==============================================================================
# Main Execution Pipeline
# ==============================================================================
def main():
    input_file = "phase2_data.joblib"
    if not os.path.exists(input_file):
        raise FileNotFoundError(f"Missing '{input_file}'. Please run phase2_preprocessing.py first!")

    print(f"Loading preprocessed data from '{input_file}'...")
    data = joblib.load(input_file)
    train_df      = data['train_df']
    dev_df        = data['dev_df']
    test_df       = data['test_df']
    class_weights = data['class_weights']
    label2id      = data['label2id']

    criterion_test = nn.CrossEntropyLoss(weight=class_weights.to(DEVICE))
    target_names   = list(label2id.keys())

    # --------------------------------------------------------------------------
    # Baseline A: XLM-RoBERTa
    # --------------------------------------------------------------------------
    print("\nPreparing DataLoaders for Baseline A (XLM-RoBERTa)...")
    xlmr_tokenizer = AutoTokenizer.from_pretrained("xlm-roberta-base")

    xlmr_train_dataset = TanglishDataset(train_df, xlmr_tokenizer, max_len=MAX_LEN)
    xlmr_dev_dataset   = TanglishDataset(dev_df, xlmr_tokenizer, max_len=MAX_LEN)
    xlmr_test_dataset  = TanglishDataset(test_df, xlmr_tokenizer, max_len=MAX_LEN)

    xlmr_train_loader = DataLoader(xlmr_train_dataset, batch_size=BATCH_SIZE, shuffle=True)
    xlmr_dev_loader   = DataLoader(xlmr_dev_dataset, batch_size=BATCH_SIZE, shuffle=False)
    xlmr_test_loader  = DataLoader(xlmr_test_dataset, batch_size=BATCH_SIZE, shuffle=False)

    xlmr_model, best_dev_f1_xlmr = run_training("xlm-roberta-base", xlmr_train_loader, xlmr_dev_loader, class_weights, label2id)
    _, test_f1_xlmr, xlmr_preds, xlmr_labels = evaluate(xlmr_model, xlmr_test_loader, criterion_test, DEVICE)

    print(f"\n📊 --- Baseline A (XLM-RoBERTa) Test Results ---")
    print(f"Test Macro F1: {test_f1_xlmr:.4f}\n")
    print(classification_report(xlmr_labels, xlmr_preds, target_names=target_names, digits=4, zero_division=0))
    torch.save(xlmr_model.state_dict(), "xlmr_baseline.pt")

    # --------------------------------------------------------------------------
    # Baseline B: MuRIL Sentence-Only
    # --------------------------------------------------------------------------
    print("\nPreparing DataLoaders for Baseline B (MuRIL Sentence-Only)...")
    muril_tokenizer = AutoTokenizer.from_pretrained("google/muril-base-cased")

    muril_train_dataset = TanglishDataset(train_df, muril_tokenizer, max_len=MAX_LEN)
    muril_dev_dataset   = TanglishDataset(dev_df, muril_tokenizer, max_len=MAX_LEN)
    muril_test_dataset  = TanglishDataset(test_df, muril_tokenizer, max_len=MAX_LEN)

    muril_train_loader = DataLoader(muril_train_dataset, batch_size=BATCH_SIZE, shuffle=True)
    muril_dev_loader   = DataLoader(muril_dev_dataset, batch_size=BATCH_SIZE, shuffle=False)
    muril_test_loader  = DataLoader(muril_test_dataset, batch_size=BATCH_SIZE, shuffle=False)

    muril_model, best_dev_f1_muril = run_training("google/muril-base-cased", muril_train_loader, muril_dev_loader, class_weights, label2id)
    _, test_f1_muril, muril_preds, muril_labels = evaluate(muril_model, muril_test_loader, criterion_test, DEVICE)

    print(f"\n📊 --- Baseline B (MuRIL Sentence-Only) Test Results ---")
    print(f"Test Macro F1: {test_f1_muril:.4f}\n")
    print(classification_report(muril_labels, muril_preds, target_names=target_names, digits=4, zero_division=0))
    torch.save(muril_model.state_dict(), "muril_baseline.pt")

    # --------------------------------------------------------------------------
    # Comparison & Saving Output
    # --------------------------------------------------------------------------
    comparison_df = pd.DataFrame({
        "Baseline Model": ["Baseline A: XLM-RoBERTa", "Baseline B: MuRIL (Sentence-Only)"],
        "Dev Macro F1": [f"{best_dev_f1_xlmr:.4f}", f"{best_dev_f1_muril:.4f}"],
        "Test Macro F1": [f"{test_f1_xlmr:.4f}", f"{test_f1_muril:.4f}"]
    })

    print("=" * 65)
    print("            BASELINE MODELS PERFORMANCE COMPARISON            ")
    print("=" * 65)
    print(comparison_df.to_string(index=False))
    print("=" * 65)

    output_file = "phase3_results.joblib"
    joblib.dump({
        "test_f1_xlmr": test_f1_xlmr,
        "test_f1_muril": test_f1_muril,
        "best_dev_f1_xlmr": best_dev_f1_xlmr,
        "best_dev_f1_muril": best_dev_f1_muril
    }, output_file)
    print(f"\n✅ Phase 3 completed successfully! Saved baseline results to '{output_file}'.")

if __name__ == "__main__":
    main()
